### ISSUE TITLE
New update completely changes syntax coloring

### ISSUE THREAD

**Issue by chasegiunta** [dustinsanders/an-old-hope-theme-vscode#14]
There's not a real changelog to go off of, but this new update really killed the awesomeness of this great theme. Is there a config we can set to get the old syntax color rules back?

**Comment by dustinsanders** [comment]
Some actual constructive criticism would be nice, not just `really killed the awesomeness`. Regardless I just published an update with version 3.0.1 that includes `An Old Hope Classic`

**Comment by chasegiunta** [comment]
For sure, you're right. VScode auto-updating extensions, and the shock effect from this theme change didn't play well with me, I apologize for that, but since it _did_ auto update on me, and I couldn't refer back to changes, there wasn't much constructive criticism I could offer.

<img width="541" alt="screen shot 2017-10-18 at 11 13 17 am" src="https://user-images.githubusercontent.com/1377169/31729930-11265008-b3f6-11e7-81d8-40414e130eb2.png">
<img width="540" alt="screen shot 2017-10-18 at 10 14 05 am" src="https://user-images.githubusercontent.com/1377169/31729940-16409300-b3f6-11e7-942a-6bedca9eb18b.png">

These are all preference, but I really dug the red color tone you used throughout. The new update removed most of that in favor of the green. I also preferred the quotes being same color as the content it contained.

<img width="489" alt="screen shot 2017-10-18 at 11 14 21 am" src="https://user-images.githubusercontent.com/1377169/31730092-75d5b868-b3f6-11e7-819e-c6571cafd165.png">

<img width="498" alt="screen shot 2017-10-18 at 10 14 20 am" src="https://user-images.githubusercontent.com/1377169/31730104-81e5d8d6-b3f6-11e7-9ca2-5852e86da8ef.png">

I don't know what the theme has control over, and what it doesn't. And obviously you cannot account for every language / syntax. I do welcome most the change in this example with the additional coloring, but again, the absence of that great red color is very apparent.

Very subjective, I know. Potentially there's a way to alleviate these personal nitpicks that I'm unaware of? Appreciate your work.

**Comment by dustinsanders** [comment]
Thanks for the feedback. I agree that the quotes should be the same color as the string. Now regarding xml tags being green, I was trying to account for the following [`issue`](https://github.com/dustinsanders/an-old-hope-theme-vscode/issues/9). But I can see how if you are not using React the theme could be overly green. There are a few options to remedy this. First I could make React Class components and standard tags all red. Also I could make the custom tags green and the standard html tags red. Let me play with it a bit, and I'll push out another update.

**Comment by dustinsanders** [comment]
Also what do you think of the `<>` in xml and `{%}` in your bottom example now being blue instead of the foreground color?

**Comment by chasegiunta** [comment]
@dustinsanders You know, I think I probably still like the delimiters being the foreground color. In my limited examples, they would be the only items not colored. The attributes in that example (`parameters` `relatedToParams`, etc) being colored is still welcome, on my end. I wonder if they would benefit from being the red and moving the yellow back to these 
![image](https://user-images.githubusercontent.com/1377169/31777236-34fecae2-b4b3-11e7-8e58-9a3b48a373df.png)

I'm apparently not a huge fan of the orange, but I like it being used to highlight these values 
![image](https://user-images.githubusercontent.com/1377169/31777277-501c20e0-b4b3-11e7-96cb-bfd5120c69c0.png)

I wish I could dig in and toy with it more. Sorry if this is kinda impossible to implement or if I'm drifting too much toward the previous version.
