### ISSUE TITLE
editor.findMatchBackground is same color as text -- causing single rectangle of hilighting

### ISSUE THREAD

**Issue by s-kem** [dustinsanders/an-old-hope-theme-vscode#15]
Hey Dustin, can submit a PR for this if you want, but not sure how to test locally.

Recently updating either this or vscode has caused my find-all hilights to just be blue rectangles, because the `editor.findMatchBackground` value is the same as the default text.

Adding ` "editor.findMatchBackground": "#3f4044"` to my preferences fixed it, so my assumption here is if you just used the ` "editor.findMatchBackground": secondary` it'd fix it.

Before:

<img width="380" alt="screen shot 2017-10-31 at 9 11 08 am" src="https://user-images.githubusercontent.com/8228066/32228227-ab282d50-be1b-11e7-9b65-fdb52bc0d9e2.png">

After:

<img width="393" alt="screen shot 2017-10-31 at 9 17 51 am" src="https://user-images.githubusercontent.com/8228066/32228504-6854d28e-be1c-11e7-840f-866052c4e129.png">

**Comment by dustinsanders** [comment]
Good catch Sean! This should be a one-line fix. Should be able to cut a new release today.

**Comment by dustinsanders** [comment]
Sean, this should be fixed with v3.1.1, let me know if it did not fix your issue
