### ISSUE TITLE
Invisible text in terminal

### ISSUE THREAD

**Issue by usernamehw** [dustinsanders/an-old-hope-theme-vscode#16]
One example is running Mocha tests:
![invisible_text](https://user-images.githubusercontent.com/9638156/34643597-e05d6228-f337-11e7-929f-6c51f41f4353.png)

Corresponding property: `"terminal.ansiBrightBlack"`

I guess, `"terminal.ansiBlack"` is invisible too.

**Comment by dustinsanders** [comment]
Tied up with work currently. I can provide instructions on running locally if you would like to attempt a PR?

**Comment by dustinsanders** [comment]
Sorry for taking so long to merge the PR. Your changes should be reflected in v3.2.0, please let me know if you see any issues.
