### ISSUE TITLE
Italic Font in Markdown

### ISSUE THREAD

**Issue by joncalhoun** [dustinsanders/an-old-hope-theme-vscode#18]
By default, all font in a markdown file is italic with this theme. If I change to another team it fixes the issue, so I'm guessing it is a setting somewhere in this theme.

Any ideas on how to fix this in a PR? I don't know where to look but would be willing to try to help if I can figure out what needs changed.

**Comment by dustinsanders** [comment]
I think I know the issue, could you provide me some sample markdown? If so I will provide back to you a screenshot of my changes, and if it looks good I will publish it.

**Comment by joncalhoun** [comment]
It only happens in "An Old Hope" (not in classic or the light versions) and it is *all* text.

![](https://www.dropbox.com/s/ewo5zxs42250pdv/Screenshot%202018-03-04%2016.02.36.png?dl=0&raw=1)

vs

![](https://www.dropbox.com/s/yfr77e7uu61vjtw/Screenshot%202018-03-04%2016.02.59.png?dl=0&raw=1)

**Comment by joncalhoun** [comment]
As you can see, even titles are italic. It looks like all font is just italic by default.

**Comment by dustinsanders** [comment]
Just published v3.2.1 let me know if this fixes your issue.

**Comment by joncalhoun** [comment]
Appears to be fixed. Thanks so much!
