### ISSUE TITLE
Makefile '${' renders doesn't color closing }

### ISSUE THREAD

**Issue by iancullinane** [dustinsanders/an-old-hope-theme-vscode#19]
For instance something like this:

```Makefile
all: clean client-docker
	@echo "Build container ${NAME} in ${ENVIRONMENT}"
        build command args ...
```

where all the opening brackets are colored but the closing } is not

For example:

<img width="485" alt="screen shot 2018-06-16 at 10 24 54 am" src="https://user-images.githubusercontent.com/3598675/41499547-d55f0b92-714f-11e8-93de-cb6a74cc4780.png">

**Comment by black-black-cat** [comment]
Looks find now. @iancullinane @dustinsanders 

![chrome_QjclQE54AA](https://user-images.githubusercontent.com/15521864/66696325-a45dc300-ecfd-11e9-8d46-f03aa0bd652f.png)
