### ISSUE TITLE
Separation between the editor and terminal

### ISSUE THREAD

**Issue by nsticco** [dustinsanders/an-old-hope-theme-vscode#23]
I would love for the theme to have some separation between the terminal and editor windows in the form of a color difference or a dividing line. Right now, it's difficult to hunt for the edge to resize.

Alternatively, if anyone can point me to how to change this without changing the editor's background color, I would also appreciate it... (Changing the "terminal.background" color doesn't seem to change the terminal header background color).

**Comment by dustinsanders** [comment]
I just published v4.3.0. Can you confirm that this is what you were looking for?

**Comment by nsticco** [comment]
Yes, perfect!
