### ISSUE TITLE
New theme update on VSCode 

### ISSUE THREAD

**Issue by jjsub** [dustinsanders/an-old-hope-theme-vscode#24]
Hello, 

I don't have a better way to contact the creator of this theme. 

The new update that came out today on VSCode for this theme is making things less readable. The color scheme before the update is very good and I used it for years now. 

Please if there is any way that I can help to support this theme or to get the old version on the VSCode store? 

Thanks 

![Screen Shot 2020-03-17 at 6 51 54 PM](https://user-images.githubusercontent.com/7912104/76912154-d3fe9180-6880-11ea-93d4-db8666d9e3e5.png)

**Comment by brienpafford** [comment]
Bump

**Comment by dustinsanders** [comment]
It has nothing to do with the theme, it is because of the latest vscode release. You can learn more [here](https://github.com/microsoft/vscode/issues/92308)

In the meantime you should be able to make the following change in your settings, `"editor.semanticHighlighting.enabled": false`

**Comment by jjsub** [comment]
Thanks for pointing me to this solution! 

Great job with this theme. I really like it.

**Comment by dustinsanders** [comment]
Looks like vscode has been updated, take a look [here](https://github.com/microsoft/vscode/issues/92740)
