### ISSUE TITLE
Cannot Tell Which Editor Is Active

### ISSUE THREAD

**Issue by cfchris** [dustinsanders/an-old-hope-theme-vscode#25]
Firstly, this is _probably_ because of a VS Code update (and not your fault).

Just getting back into Flutter Dev after several months off. Noticed I _could not_ tell which edit tab was in focus.

In "An Old Hope Classic", I can see the difference.

![image](https://user-images.githubusercontent.com/819847/124840551-18afaf80-df40-11eb-808f-c2a742726428.png)

In "An Old Hope", I cannot tell which tab is active.

![image](https://user-images.githubusercontent.com/819847/124840632-485eb780-df40-11eb-8dd1-346812fc57fb.png)

This seems to be true in Windows and Linux for me.

**Comment by dustinsanders** [comment]
Are you still seeing this issue? I'm not able to recreate. In my editor I see a blue underline. 
<img width="583" alt="Screen Shot 2021-07-16 at 8 15 27 PM" src="https://user-images.githubusercontent.com/15836012/126021115-061d431d-67b7-4433-bd30-bde59cca1745.png">

**Comment by dustinsanders** [comment]
disregard the previous comment. I just released v4.4

**Comment by cfchris** [comment]
This is fixed. Thank you so much!
