### ISSUE TITLE
`this` as reserved word color

### ISSUE THREAD

**Issue by allangomes** [dustinsanders/an-old-hope-theme-vscode#4]
`this` as reserved word color in JS,TS....

**Comment by dustinsanders** [comment]
I need some more details. Could you provide a screenshot of a theme that handles it in the manner you are describing?

**Comment by allangomes** [comment]
hi, here is an example. my suggestion is that `this` is a reserved word (`green` or `red` color)

<img width="240" alt="screen shot 2017-03-01 at 18 58 48" src="https://cloud.githubusercontent.com/assets/877723/23484199/c2db147a-feb4-11e6-83b6-0b449f3596a1.png">

**Comment by dustinsanders** [comment]
It is my understanding that the language grammar defines what is a reserved word. Can you provide a link to another theme that handles this correctly?

**Comment by chapmandu** [comment]
I too would be grateful if the reserved words were coloured (in my case the `local` scope). The Dark (Visual Studio) theme handles this as described.

https://github.com/Microsoft/vscode/tree/master/extensions/theme-monokai

<img width="427" alt="screen shot 2017-05-08 at 9 33 41 pm" src="https://cloud.githubusercontent.com/assets/1092563/25802741/082d55ee-3437-11e7-9d23-f87d942a7a8e.png">

Thanks for the port!

**Comment by dustinsanders** [comment]
I'm hoping to convert the theme to use the new [theme generator](https://github.com/Tyriar/vscode-theme-generator). Hopefully that will fix the above issue, I will keep an eye out when attempting.

**Comment by dustinsanders** [comment]
This should be fixed with the 3.x.x release.
