### ISSUE TITLE
broken comment gray

### ISSUE THREAD

**Issue by polizz** [dustinsanders/an-old-hope-theme-vscode#5]
It looks like the latest vscode broke the comment coloring.

<img width="380" alt="screen shot 2017-02-14 at 9 22 38 am" src="https://cloud.githubusercontent.com/assets/10888433/22935121/256324cc-f297-11e6-8033-e5376b2fa3cb.png">

**Comment by dustinsanders** [comment]
I'm not seeing an issue(see below), are you sure it is not an issue with your javascript grammar. I'm using the bundled javascript grammar with vscode.

<img width="676" alt="screen shot 2017-02-28 at 4 42 02 pm" src="https://cloud.githubusercontent.com/assets/15836012/23437785/0351e000-fdd5-11e6-9b8d-da04d4107ad8.png">

**Comment by polizz** [comment]
Sounds good
