### ISSUE TITLE
markdown support

### ISSUE THREAD

**Issue by leecz** [dustinsanders/an-old-hope-theme-vscode#6]
如题

**Comment by dustinsanders** [comment]
[done](https://github.com/dustinsanders/an-old-hope-theme-vscode/commit/255ee37ae46461516c614ed0d210c176e13846b5). Let me know if anything looks off.

**Comment by leecz** [comment]
@dustinsanders  thanks! 
All looks great , only inline code (`back-ticks around`) not highlight.
👍
