### ISSUE TITLE
Lack of colors on typescript files

### ISSUE THREAD

**Issue by lednhatkhanh** [dustinsanders/an-old-hope-theme-vscode#7]
![capture](https://cloud.githubusercontent.com/assets/9303093/23589006/763a162e-01f8-11e7-948f-191c3cdf579b.PNG)

**Comment by dustinsanders** [comment]
I'm not familiar with TypeScript and what it should look like. I'm open to a pull request though.

**Comment by polizz** [comment]
@lednhatkhanh are you running a Babel syntax extension? If so, which one?

**Comment by dustinsanders** [comment]
see 3.x.x release
