### ISSUE TITLE
Sintax coloring for JSX components

### ISSUE THREAD

**Issue by allangomes** [dustinsanders/an-old-hope-theme-vscode#9]
Hi, first of all I wanted to highlight your excellent work, by far this is the best theme I found in vscode.

The Microsoft released vscode Jun 2017, a highlight for JSX components

<img width="217" alt="screen shot 2017-06-09 at 14 54 40" src="https://user-images.githubusercontent.com/877723/26988051-3d03c6f8-4d24-11e7-9fcc-21a5031bcd0f.png">

As you can see `<div>` is different color because this is a Html element
Already the `Container` and others, are React/JSX component

More details in https://code.visualstudio.com/updates/v1_13#_languages

**Comment by dustinsanders** [comment]
Would you like to try a PR? I'm hoping to move this project to the [theme generator](https://github.com/Tyriar/vscode-theme-generator) soon.

**Comment by dustinsanders** [comment]
Check out 3.x.x release
